# Generated by Django 4.1 on 2023-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_co2'),
    ]

    operations = [
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captime', models.DateTimeField()),
                ('caphumidity', models.CharField(max_length=10)),
            ],
        ),
    ]
